name: CI Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      # Both steps now point to your 'frontend' folder
      - name: Install dependencies
        working-directory: './frontend'
        run: npm ci
      
      - name: Run tests
        working-directory: './frontend'
        run: npm test